#ifndef _BBSH_SRC_COMMONS_H
#define _BBSH_SRC_COMMONS_H

#define BBSH_VERSION_MAJOR "0"
#define BBSH_VERSION_MINOR "1"
#define BBSH_VERSION_DEBUG "0"

#define BBSH_VERSION_STR "v"BBSH_VERSION_MAJOR"."\
        BBSH_VERSION_MINOR"."BBSH_VERSION_DEBUG

#endif